apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- if not .Values.multiNamespaceMode }}
  name: {{ include "spark.fullname" . }}-pod-launcher-role
  namespace: "{{ .Release.Namespace }}"
  {{- else }}
  name: {{ .Release.Namespace }}-{{ include "spark.fullname" . }}-pod-launcher-role
  {{- end }}
  labels:
    tier: spark
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- if .Values.multiNamespaceMode }}
    namespace: "{{ .Release.Namespace }}"
    {{- end }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"